"""Initial

Revision ID: 6bb3a3cce8b9
Revises: 
Create Date: 2024-08-30 17:59:37.775217

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6bb3a3cce8b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('fio', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_author'))
    )
    op.create_table('poem',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('author_uuid', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['author_uuid'], ['author.uuid'], name=op.f('fk_poem_author_uuid_author')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_poem'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poem')
    op.drop_table('author')
    # ### end Alembic commands ###
